
target:
	mpicc -g -Wall -o ./bin/3_0 3_0.c
	mpicc -g -Wall -o ./bin/3_1 3_1.c
	mpicc -g -Wall -o ./bin/3_2_a 3_2_a.c
	mpicc -g -Wall -o ./bin/3_2_b 3_2_b.c
	mpicc -g -Wall -o ./bin/3_2_d 3_2_d.c


clean:
	rm -rf ./bin/*
	

