target:
	gcc -Wall -o ./bin/4.1_pth_pi_mutex 4.1_pth_pi_mutex.c
	gcc -Wall -o ./bin/4.2_pth_pi_mutex 4.2_pth_pi_mutex.c
	gcc -Wall -o ./bin/4_3_a 4_3_a.c
	gcc -Wall -o ./bin/4_3_b 4_3_b.c
	gcc -Wall -o ./bin/4_3_c 4_3_c.c

clean:
	rm -rf ./bin/*